---
 - hosts: python2 
   become: yes
   user: root 
   roles: 
    - nginx
    - itcraftsmanpl.php7
    - geerlingguy.memcached 
    - geerlingguy.git
    - geerlingguy.composer
    - tersmitten.htop
    - tips-config
